### ISSUE TITLE
Save Function Breaks

### ISSUE THREAD

**Issue by BP-0321** [ndilday/OnlyWar#11]
Pressing Save stops saying "Saved!"

Can continue playing fine but once the game is closed you will not be able to load the game.

Heres a save from before i close the game
[default.zip](https://github.com/ndilday/OnlyWar/files/7811379/default.zip)
[Player.log](https://github.com/ndilday/OnlyWar/files/7811380/Player.log)
.

**Comment by ndilday** [comment]
In your log file, I'm seeing several "IOException: The process cannot access the file 'C:\Users\[redacted]\Desktop\Only War\Only War The Next Chapter_Data\StreamingAssets\Saves\default.s3db' because it is being used by another process." I use SQLite for save files, and I get this exception when I have the save file open in the editor when I go to save. Did you have the file open in anything that would prevent write access when you went to save?

**Comment by ndilday** [comment]
Also, this log is helping me uncover some other unrelated bugs, so thanks for that!

**Comment by BP-0321** [comment]
I didnt have anything else open, but glad its working out!!

**Comment by ndilday** [comment]
Okay, I have a guess that a failed DB commit earlier in the log could be the culprit. I've fixed that bug for the next version.
